// automatically generated by the FlatBuffers compiler, do not modify

package UnrealCoojaMsg;

public final class MsgType {
  private MsgType() { }
  public static final byte LED = 1;
  public static final byte LOCATION = 2;
  public static final byte RADIO = 3;
  public static final byte RADIO_STATE = 4;
  public static final byte PIR = 5;
  public static final byte PAUSE = 6;
  public static final byte RESUME = 7;
  public static final byte SPEED_NORM = 8;
  public static final byte SPEED_SLOW = 9;
  public static final byte SPEED_FAST = 10;
  public static final byte RADIO_DUTY = 11;
  public static final byte FIRE = 12;
  public static final byte TEMP = 13;
  public static final byte SMOKE = 14;

  public static final String[] names = { "LED", "LOCATION", "RADIO", "RADIO_STATE", "PIR", "PAUSE", "RESUME", "SPEED_NORM", "SPEED_SLOW", "SPEED_FAST", "RADIO_DUTY", "FIRE", "TEMP", "SMOKE", };

  public static String name(int e) { return names[e - LED]; }
}

